# Use uma imagem base adequada
FROM python:3.12

# Instale as dependências do sistema necessárias
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Configure o ambiente
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Crie e ative o ambiente virtual
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de requisitos e instale dependências Python
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copie o restante dos arquivos do projeto
COPY . /app/

# Comando para iniciar o servidor
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]