# Generated by Django 5.0.3 on 2024-04-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idClient', models.UUIDField(primary_key=True, serialize=False)),
                ('nomeRazao', models.CharField(max_length=100)),
                ('cpfCnpj', models.CharField(max_length=16)),
                ('rg', models.CharField(max_length=16)),
                ('dataNascFund', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('confirmarEmail', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
