# Generated by Django 5.0.3 on 2024-09-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idClient', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nomeRazao', models.CharField(max_length=100)),
                ('cpfCnpj', models.CharField(max_length=16, unique=True)),
                ('rg', models.CharField(max_length=16, unique=True)),
                ('dataNascFund', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirmarEmail', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('idVeiculo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('tipoVeiculo', models.CharField(max_length=20)),
                ('anoFabricacao', models.CharField(max_length=4)),
                ('anoModelo', models.CharField(max_length=4)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
