# Generated by Django 5.0.3 on 2024-10-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('idSchedule', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dtaAgendamento', models.DateField()),
                ('observacao', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('idVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
