# Generated by Django 5.0.3 on 2024-04-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_person_idclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dataNascFund',
            field=models.CharField(max_length=10),
        ),
    ]
