# Generated by Django 5.0.3 on 2024-10-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='horaAgendamento',
            field=models.CharField(default='00:00', max_length=6),
        ),
        migrations.AddField(
            model_name='schedule',
            name='localAgendamento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='observacao',
            field=models.CharField(max_length=100),
        ),
    ]
