# Generated by Django 5.0.3 on 2024-05-01 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_datanascfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='confirmarEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpfCnpj',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('idVeiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('tipoVeiculo', models.CharField(max_length=20)),
                ('anoFabricacao', models.CharField(max_length=4)),
                ('anoModelo', models.CharField(max_length=4)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
