# Generated by Django 5.0.3 on 2024-05-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_person_confirmaremail_alter_person_cpfcnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='idClient',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='rg',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='idVeiculo',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
