# Generated by Django 5.0.3 on 2025-03-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_bairro_person_cep_person_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='complemento',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
