# Generated by Django 5.0.3 on 2024-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_person_idclient_alter_vehicle_idveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dataNascFund',
            field=models.DateField(),
        ),
    ]
