# Generated by Django 5.0.3 on 2025-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_person_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sexo',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
