# Generated by Django 5.0.3 on 2025-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_person_sexo_alter_person_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sexo',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
