# Generated by Django 5.0.3 on 2024-05-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_person_datanascfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
